services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: habibi2023
      MYSQL_DATABASE: streamer_golang
      MYSQL_USER: ilia
      MYSQL_PASSWORD: Hbk2017qqw.
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
