version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - app-storage:/app/storage
    container_name: app
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: habibi2023
      MYSQL_DATABASE: streamer_golang
      MYSQL_USER: ilia
      MYSQL_PASSWORD: Hbk2017qqw.
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: mysql_database

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - app-storage:/app/storage
    container_name: nginx
    depends_on:
      - app
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "8080:8000"
      - "9443:9443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    restart: always

volumes:
  mysql-data:
  app-storage:
  portainer_data:
